//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpreader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cpreader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string cart_add {
            get {
                return ResourceManager.GetString("cart_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been added to the cart..
        /// </summary>
        internal static string cart_added {
            get {
                return ResourceManager.GetString("cart_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string cart_close {
            get {
                return ResourceManager.GetString("cart_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items copied to the clipboard..
        /// </summary>
        internal static string cart_copied {
            get {
                return ResourceManager.GetString("cart_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy CPR Numbers.
        /// </summary>
        internal static string cart_copy {
            get {
                return ResourceManager.GetString("cart_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Number.
        /// </summary>
        internal static string cart_cprnumber {
            get {
                return ResourceManager.GetString("cart_cprnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart emptied..
        /// </summary>
        internal static string cart_emptied {
            get {
                return ResourceManager.GetString("cart_emptied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Cart.
        /// </summary>
        internal static string cart_empty {
            get {
                return ResourceManager.GetString("cart_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has aready been added to the cart..
        /// </summary>
        internal static string cart_exists {
            get {
                return ResourceManager.GetString("cart_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string cart_items {
            get {
                return ResourceManager.GetString("cart_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string cart_name {
            get {
                return ResourceManager.GetString("cart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no items in the cart.
        /// </summary>
        internal static string cart_noitems {
            get {
                return ResourceManager.GetString("cart_noitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not removed from the cart..
        /// </summary>
        internal static string cart_notremoved {
            get {
                return ResourceManager.GetString("cart_notremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string cart_remove {
            get {
                return ResourceManager.GetString("cart_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed from the cart..
        /// </summary>
        internal static string cart_removed {
            get {
                return ResourceManager.GetString("cart_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the selected numbers to copy.
        /// </summary>
        internal static string cart_rightclick {
            get {
                return ResourceManager.GetString("cart_rightclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CPR Numbers.
        /// </summary>
        internal static string cart_select {
            get {
                return ResourceManager.GetString("cart_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string cart_select_title {
            get {
                return ResourceManager.GetString("cart_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View cart.
        /// </summary>
        internal static string cart_view {
            get {
                return ResourceManager.GetString("cart_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes ingen informationer om den pågældende person i CPR Brokeren..
        /// </summary>
        internal static string error_503 {
            get {
                return ResourceManager.GetString("error_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltet {0} skal udfyldes.
        /// </summary>
        internal static string error_required {
            get {
                return ResourceManager.GetString("error_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forkert brugernavn eller adgangskode.
        /// </summary>
        internal static string login_invalid_credientials {
            get {
                return ResourceManager.GetString("login_invalid_credientials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har ikke tilladelse til at benytte applikationen.
        /// </summary>
        internal static string login_not_authorized {
            get {
                return ResourceManager.GetString("login_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPReader - Log på.
        /// </summary>
        internal static string login_pagetitle {
            get {
                return ResourceManager.GetString("login_pagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log på.
        /// </summary>
        internal static string login_submit {
            get {
                return ResourceManager.GetString("login_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indtast venligst dine oplysninger.
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikationen havde en uventet fejl.
        /// </summary>
        internal static string login_unexpected_error {
            get {
                return ResourceManager.GetString("login_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er nu logget ud.
        /// </summary>
        internal static string logout_succesful {
            get {
                return ResourceManager.GetString("logout_succesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string nav_help {
            get {
                return ResourceManager.GetString("nav_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string nav_logout_button {
            get {
                return ResourceManager.GetString("nav_logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string nav_quicksearch_addresslaceholder {
            get {
                return ResourceManager.GetString("nav_quicksearch_addresslaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an address when searching online.
        /// </summary>
        internal static string nav_quicksearch_addressrequired {
            get {
                return ResourceManager.GetString("nav_quicksearch_addressrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        internal static string nav_quicksearch_invalidaddress {
            get {
                return ResourceManager.GetString("nav_quicksearch_invalidaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string nav_quicksearch_local {
            get {
                return ResourceManager.GetString("nav_quicksearch_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string nav_quicksearch_online {
            get {
                return ResourceManager.GetString("nav_quicksearch_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR or name.
        /// </summary>
        internal static string nav_quicksearch_placeholder {
            get {
                return ResourceManager.GetString("nav_quicksearch_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string nav_quicksearch_submit {
            get {
                return ResourceManager.GetString("nav_quicksearch_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPReader.
        /// </summary>
        internal static string nav_title {
            get {
                return ResourceManager.GetString("nav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ID Code.
        /// </summary>
        internal static string person_address_danishAddress_countryIdentificationCode {
            get {
                return ResourceManager.GetString("person_address_danishAddress_countryIdentificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Note.
        /// </summary>
        internal static string person_address_danishAddress_danishNote {
            get {
                return ResourceManager.GetString("person_address_danishAddress_danishNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string person_address_danishAddress_districtName {
            get {
                return ResourceManager.GetString("person_address_danishAddress_districtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdivision.
        /// </summary>
        internal static string person_address_danishAddress_districtSubdivision {
            get {
                return ResourceManager.GetString("person_address_danishAddress_districtSubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string person_address_danishAddress_floor {
            get {
                return ResourceManager.GetString("person_address_danishAddress_floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specielvejkode.
        /// </summary>
        internal static string person_address_danishAddress_isSpecielVejkode {
            get {
                return ResourceManager.GetString("person_address_danishAddress_isSpecielVejkode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt adresse.
        /// </summary>
        internal static string person_address_danishAddress_isUkendtAdresse {
            get {
                return ResourceManager.GetString("person_address_danishAddress_isUkendtAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sub Location.
        /// </summary>
        internal static string person_address_danishAddress_mailSubLocaltion {
            get {
                return ResourceManager.GetString("person_address_danishAddress_mailSubLocaltion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Code.
        /// </summary>
        internal static string person_address_danishAddress_municipalityCode {
            get {
                return ResourceManager.GetString("person_address_danishAddress_municipalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string person_address_danishAddress_note {
            get {
                return ResourceManager.GetString("person_address_danishAddress_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politidistrikt.
        /// </summary>
        internal static string person_address_danishAddress_politiDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_politiDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string person_address_danishAddress_postCode {
            get {
                return ResourceManager.GetString("person_address_danishAddress_postCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postdistrikt.
        /// </summary>
        internal static string person_address_danishAddress_postDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_postDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box.
        /// </summary>
        internal static string person_address_danishAddress_postOfficeBox {
            get {
                return ResourceManager.GetString("person_address_danishAddress_postOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skoledistrikt.
        /// </summary>
        internal static string person_address_danishAddress_skoleDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_skoleDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socialdistrikt.
        /// </summary>
        internal static string person_address_danishAddress_socialDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_socialDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sognedistrikt.
        /// </summary>
        internal static string person_address_danishAddress_sogneDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_sogneDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string person_address_danishAddress_streetBuilding {
            get {
                return ResourceManager.GetString("person_address_danishAddress_streetBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building ID.
        /// </summary>
        internal static string person_address_danishAddress_streetBuildingIdentifier {
            get {
                return ResourceManager.GetString("person_address_danishAddress_streetBuildingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Code.
        /// </summary>
        internal static string person_address_danishAddress_streetCode {
            get {
                return ResourceManager.GetString("person_address_danishAddress_streetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        internal static string person_address_danishAddress_streetName {
            get {
                return ResourceManager.GetString("person_address_danishAddress_streetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressing Name.
        /// </summary>
        internal static string person_address_danishAddress_streetNameForAddressing {
            get {
                return ResourceManager.GetString("person_address_danishAddress_streetNameForAddressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        internal static string person_address_danishAddress_suite {
            get {
                return ResourceManager.GetString("person_address_danishAddress_suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgdistrikt.
        /// </summary>
        internal static string person_address_danishAddress_valgkredsDistrikt {
            get {
                return ResourceManager.GetString("person_address_danishAddress_valgkredsDistrikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landekode.
        /// </summary>
        internal static string person_address_greenlandicAddress_countryIdentificationCode {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_countryIdentificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string person_address_greenlandicAddress_districtName {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_districtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forstad.
        /// </summary>
        internal static string person_address_greenlandicAddress_districtSubdivision {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_districtSubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etage.
        /// </summary>
        internal static string person_address_greenlandicAddress_floor {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specielvejkode.
        /// </summary>
        internal static string person_address_greenlandicAddress_isSpecielVejkode {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_isSpecielVejkode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt adresse.
        /// </summary>
        internal static string person_address_greenlandicAddress_isUkendtAdresse {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_isUkendtAdresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunekode.
        /// </summary>
        internal static string person_address_greenlandicAddress_municipalityCode {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_municipalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string person_address_greenlandicAddress_note {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string person_address_greenlandicAddress_postCode {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_postCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadenummer.
        /// </summary>
        internal static string person_address_greenlandicAddress_streetBuilding {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_streetBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vejkode.
        /// </summary>
        internal static string person_address_greenlandicAddress_streetCode {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_streetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadenavn.
        /// </summary>
        internal static string person_address_greenlandicAddress_streetName {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_streetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresseforadressering.
        /// </summary>
        internal static string person_address_greenlandicAddress_streetNameForAddressing {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_streetNameForAddressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        internal static string person_address_greenlandicAddress_suite {
            get {
                return ResourceManager.GetString("person_address_greenlandicAddress_suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt adresse.
        /// </summary>
        internal static string person_address_worldAddress_isUkendtAdresseIndikator {
            get {
                return ResourceManager.GetString("person_address_worldAddress_isUkendtAdresseIndikator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        internal static string person_address_worldAddress_locationDescriptionText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_locationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string person_address_worldAddress_note {
            get {
                return ResourceManager.GetString("person_address_worldAddress_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_address_worldAddress_postalAddressFifthLineText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_postalAddressFifthLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string person_address_worldAddress_postalAddressFirstLineText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_postalAddressFirstLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_address_worldAddress_postalAddressFourthLineText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_postalAddressFourthLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_address_worldAddress_postalAddressSecondLineText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_postalAddressSecondLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_address_worldAddress_postalAddressThirdLineText {
            get {
                return ResourceManager.GetString("person_address_worldAddress_postalAddressThirdLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string person_birthdate {
            get {
                return ResourceManager.GetString("person_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Palce.
        /// </summary>
        internal static string person_birthplace {
            get {
                return ResourceManager.GetString("person_birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødereg. myndighed.
        /// </summary>
        internal static string person_birthRegisteringAuthority {
            get {
                return ResourceManager.GetString("person_birthRegisteringAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Name.
        /// </summary>
        internal static string person_callname {
            get {
                return ResourceManager.GetString("person_callname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string person_false {
            get {
                return ResourceManager.GetString("person_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string person_firstname {
            get {
                return ResourceManager.GetString("person_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string person_gender {
            get {
                return ResourceManager.GetString("person_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string person_lastname {
            get {
                return ResourceManager.GetString("person_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string person_middelname {
            get {
                return ResourceManager.GetString("person_middelname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressing Name.
        /// </summary>
        internal static string person_nameForAddressing {
            get {
                return ResourceManager.GetString("person_nameForAddressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No information).
        /// </summary>
        internal static string person_noparents {
            get {
                return ResourceManager.GetString("person_noparents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukendt adresse.
        /// </summary>
        internal static string person_otherAddress_worldAddress_isUkendtAdresseIndikator {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_isUkendtAdresseIndikator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        internal static string person_otherAddress_worldAddress_locationDescriptionText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_locationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string person_otherAddress_worldAddress_note {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_otherAddress_worldAddress_postalAddressFifthLineText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_postalAddressFifthLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string person_otherAddress_worldAddress_postalAddressFirstLineText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_postalAddressFirstLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_otherAddress_worldAddress_postalAddressFourthLineText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_postalAddressFourthLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_otherAddress_worldAddress_postalAddressSecondLineText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_postalAddressSecondLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        internal static string person_otherAddress_worldAddress_postalAddressThirdLineText {
            get {
                return ResourceManager.GetString("person_otherAddress_worldAddress_postalAddressThirdLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Of Church?.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_isMemberOfTheChurch {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_isMemberOfTheChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Address Protected?.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_isNameAddressProtected {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_isNameAddressProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Protected?.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_isPhoneNumberProtected {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_isPhoneNumberProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher Protected?.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_isResearcherProtected {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_isResearcherProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Code.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_personNationalityCode {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_personNationalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Number.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_socialSecurityNumber {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_socialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Number Active.
        /// </summary>
        internal static string person_registerInformation_cprCitizen_socialSecurityNumberActive {
            get {
                return ResourceManager.GetString("person_registerInformation_cprCitizen_socialSecurityNumberActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string person_registrationdate {
            get {
                return ResourceManager.GetString("person_registrationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See parents.
        /// </summary>
        internal static string person_showparents {
            get {
                return ResourceManager.GetString("person_showparents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Status.
        /// </summary>
        internal static string person_tilstand_civilStatusKode {
            get {
                return ResourceManager.GetString("person_tilstand_civilStatusKode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Status.
        /// </summary>
        internal static string person_tilstand_livStatusKode {
            get {
                return ResourceManager.GetString("person_tilstand_livStatusKode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string person_true {
            get {
                return ResourceManager.GetString("person_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See person.
        /// </summary>
        internal static string person_viewdetails {
            get {
                return ResourceManager.GetString("person_viewdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anden adresse.
        /// </summary>
        internal static string resultat_andenaddresse {
            get {
                return ResourceManager.GetString("resultat_andenaddresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egenskaber.
        /// </summary>
        internal static string resultat_egenskaber {
            get {
                return ResourceManager.GetString("resultat_egenskaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postadresse.
        /// </summary>
        internal static string resultat_postaddresse {
            get {
                return ResourceManager.GetString("resultat_postaddresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeroplysninger.
        /// </summary>
        internal static string resultat_registeroplysninger {
            get {
                return ResourceManager.GetString("resultat_registeroplysninger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilstande.
        /// </summary>
        internal static string resultat_tilstande {
            get {
                return ResourceManager.GetString("resultat_tilstande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der er {0} resultater på søgningen:.
        /// </summary>
        internal static string results_list_amountOfResults {
            get {
                return ResourceManager.GetString("results_list_amountOfResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste over søgeresultater fra søgning lokalt.
        /// </summary>
        internal static string results_list_local_desc_1 {
            get {
                return ResourceManager.GetString("results_list_local_desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen indeholder kun søgeresultater fra den lokale database og ikke alle CPR Registrets data..
        /// </summary>
        internal static string results_list_local_desc_2 {
            get {
                return ResourceManager.GetString("results_list_local_desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at søge bredt i CPR Registret, skal du vælge &apos;online&apos;..
        /// </summary>
        internal static string results_list_local_desc_3 {
            get {
                return ResourceManager.GetString("results_list_local_desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste over søgeresultater fra søgning online.
        /// </summary>
        internal static string results_list_online_desc_1 {
            get {
                return ResourceManager.GetString("results_list_online_desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen indeholder søgeresultater fra CPR Registret. Du kan klikke på et søgeresultat og se flere detaljer om personen..
        /// </summary>
        internal static string results_list_online_desc_2 {
            get {
                return ResourceManager.GetString("results_list_online_desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik på et søgeresultat vil desuden resultere i, at personen fremover vil optræde i lokale søgninger..
        /// </summary>
        internal static string results_list_online_desc_3 {
            get {
                return ResourceManager.GetString("results_list_online_desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fejl i søgningen.
        /// </summary>
        internal static string results_list_searchFailed {
            get {
                return ResourceManager.GetString("results_list_searchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
